### ISSUE TITLE
Home page URL cannot be used correctly

### ISSUE THREAD

**Issue by playertk** [adensW/vitesse-electron#1]
By default, Vitesse use file based routing.
the Home page url  like ‘http://localhost:3000/’
But in electron, the home page URL like a ’http://localhost:3000/index.html '
Vitesse cannot be used  ’http://localhost:3000/index.html ' and will redirect to 404Page

Is there any good way to fix this problem?
or a configuration method in electron to fix the URL reference problem?

**Comment by adensW** [comment]
in development electron home page URL use VITE_DEV_SERVER_URL like 'http://localhost:3000', but in production  use  file protocol like 'file://../renderer/index.html'.  
vite server cannot handle   ’http://localhost:3000/index.html ' with .html suffix.    use 'http://localhost:3000/index' or 'http://localhost:3000/about'  in Vitesse file based routing
you can see the code below
 https://github.com/adensW/vitesse-electron/blob/3efa049edaf98d9e44f6b33a352f60f024f79634/packages/main/src/mainWindow.ts#L30-L36
